services:
  - type: web
    name: airpollutionmonitoring
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      gunicorn --config gunicorn_config.py config.wsgi:application
    envVars:
      - key: DISABLE_COLLECTSTATIC
        value: 1  # Skip if static files already collected